const PLAYER_DATA = [
  {
    id: 1,
    name: 'John Doe',
    position: 'Shooting Guard',
    points: 22,
    rebounds: 5,
    assists: 8,
  },
  {
    id: 2,
    name: 'Jane Smith',
    position: 'Power Forward',
    points: 18,
    rebounds: 12,
    assists: 4,
  },
  {
    id: 3,
    name: 'Michael Johnson',
    position: 'Center',
    points: 14,
    rebounds: 10,
    assists: 2,
  },
  {
    id: 4,
    name: 'Samuel Green',
    position: 'Power Forward',
    points: 20,
    rebounds: 8,
    assists: 6,
  },
  {
    id: 5,
    name: 'Alex Brown',
    position: 'Point Guard',
    points: 25,
    rebounds: 3,
    assists: 9,
  },
  {
    id: 6,
    name: 'Chris Taylor',
    position: 'Shooting Guard',
    points: 19,
    rebounds: 4,
    assists: 10,
  },
  {
    id: 7,
    name: 'David King',
    position: 'Small Forward',
    points: 15,
    rebounds: 9,
    assists: 5,
  },
  {
    id: 8,
    name: 'Brian White',
    position: 'Center',
    points: 12,
    rebounds: 11,
    assists: 3,
  },
  {
    id: 9,
    name: 'Kevin Adams',
    position: 'Point Guard',
    points: 27,
    rebounds: 6,
    assists: 7,
  },
  {
    id: 10,
    name: 'Lucas Clark',
    position: 'Small Forward',
    points: 18,
    rebounds: 10,
    assists: 4,
  },
  {
    id: 11,
    name: 'Justin Lee',
    position: 'Point Guard',
    points: 16,
    rebounds: 5,
    assists: 8,
  },
  {
    id: 12,
    name: 'Matthew Hall',
    position: 'Power Forward',
    points: 21,
    rebounds: 12,
    assists: 6,
  },
];

export { PLAYER_DATA };
